### ISSUE TITLE
Updated pullAndSend.py

### ISSUE THREAD

**Issue by thetravellor** [pmudry/enphase2grafana#1]
1. Your script doesnt work with Python 3 by the way, it does work on Python 2, python 3 doesnt like you have formatted your print statements, and other errors.

2. It works on Centos 7, but only after doing this:
`sudo pip install --ignore-installed influxdb`

Otherwise Centos becomes upset with dependencies it created at install time.

3. The script run by systemd fails  under Centos

`python /home/stephen/enphase/enphase2influx/pullAndSend.py --url http://192.168.2.11/production.json &`

Removing the & makes it work just fine

4. I have modified your script to work with enphase batteries:

`lastBatteryTime=0`

`batteryData = data['storage'][0]`

`print "Time data from battery : ", batteryData['readingTime']`

`if batteryData['readingTime'] > lastBatteryTime:
          print "Pushing storage data"
          pushData(batteryData, "storage", client)
          lastBatteryTime = batteryData['readingTime']`

**Comment by thetravellor** [comment]
and 

Getting Enphase JSON information from server
Traceback (most recent call last):
  File "./pullAndSend.py", line 55, in <module>
    print ("Getting Enphase JSON information from server ") + __url__
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[stephen@family enphase2influx]$

**Comment by pmudry** [comment]
Hi,

Sorry but I don't have any CentOS release available to test. Feel free to make a pull request though for the changes that you proposed, they seem to be cool !

Regards

**Comment by pmudry** [comment]
Updated for Python3
